server:
  port: 6001
dubbo:
  application:
    name: auth-center-provider
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  provider:
    loadbalance: random